apiVersion: v1
kind: Service
metadata:
  name: pr-agent
  namespace: pr-agent
  labels:
    app: pr-agent
    component: web
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  - port: 9090
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    app: pr-agent
    component: web
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: pr-agent
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis
